# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "c4eec329c464f3f89ab78a56a47eee6271ea9d19";
    src = fetchgit {
      url = "https://github.com/rafaelmardojai/firefox-gnome-theme";
      rev = "c4eec329c464f3f89ab78a56a47eee6271ea9d19";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-EACja6V2lNh67Xvmhr0eEM/VeqM7OlTTm/81LhRbsBE=";
    };
    date = "2024-05-02";
  };
  san-francisco-pro = {
    pname = "san-francisco-pro";
    version = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
    src = fetchgit {
      url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts";
      rev = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mAXExj8n8gFHq19HfGy4UOJYKVGPYgarGd/04kUIqX4=";
    };
    date = "2021-06-22";
  };
  vesktop = {
    pname = "vesktop";
    version = "ac35f81476fc2561d437ee6e500e58e33a644c69";
    src = fetchgit {
      url = "https://github.com/Vencord/Vesktop/";
      rev = "ac35f81476fc2561d437ee6e500e58e33a644c69";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-igQU5gSTUlW4ya0Lj9nQWXEVCsO/hSt7/pJ/d5ITJJM=";
    };
    date = "2024-05-05";
  };
  waybar = {
    pname = "waybar";
    version = "231d6972d7a023e9358ab7deda509baac49006cb";
    src = fetchgit {
      url = "https://github.com/alexays/waybar";
      rev = "231d6972d7a023e9358ab7deda509baac49006cb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mCQdrn0Y3oOVZP/CileWAhuBX6aARBNrfxyqJBB4NxA=";
    };
    date = "2024-05-03";
  };
  wezterm = {
    pname = "wezterm";
    version = "18d643510fdc6e5b45da102bca5c421f28e92223";
    src = fetchgit {
      url = "https://github.com/wez/wezterm";
      rev = "18d643510fdc6e5b45da102bca5c421f28e92223";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-9UBG8cKYKhqpFiU+kYWVb25NHZ6FX5wT5xyMI0MdkEo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wezterm-18d643510fdc6e5b45da102bca5c421f28e92223/Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.3.0" = "sha256-fTpJ6uNhjmCWv7dZqVgYuS2Uic36XNYTbqlaly5QBjI=";
        "sqlite-cache-0.1.3" = "sha256-sBAC8MsQZgH+dcWpoxzq9iw5078vwzCijgyQnMOWIkk=";
      };
    };
    date = "2024-05-05";
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "91b02a1f4364a17a36c7f18b3fbe7c1c92497d07";
    src = fetchgit {
      url = "https://github.com/vinceliuice/WhiteSur-gtk-theme";
      rev = "91b02a1f4364a17a36c7f18b3fbe7c1c92497d07";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-VUPI9c7wfx+2pKThzGh/G3YWbIgWn2s7DGFA8Bxhubg=";
    };
    date = "2024-05-03";
  };
}
