name: build-all-packages

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-all-packages:
    name: Build all packages
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true
          root-reserve-mb: 512
          swap-size-mb: 1024

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V28

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch main

      - name: "Build all packages"
        run: |-
          nix flake show --json | jq  '.packages."x86_64-linux"|keys[]'| xargs -I {} nix build .#{}
