name: Nix Flake Checker

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.lua"
      - "**/*.el"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.lua"
      - "**/*.el"

jobs:
  format:
    name: Run Flake Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
