name: Update Flakes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.3
      - run: git config --global user.email "maximiliansforza@proton.me"
      - run: git config --global user.name "Maximilian Sforza"
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          git-author-name: "Maximilian Sforza"
          git-author-email: "maximiliansforza@proton.me"
          git-committer-name: "Maximilian Sforza"
          git-committer-email: "maximiliansforza@proton.me"
          token: ${{ secrets.PR_TOKEN }}
          commit-msg: "chore: Update flake.lock" # The message provided with the commit
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            automated
            keep-up-to-date
