name: "Package Update"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  nvfetcher-update:
    if: github.repository == 'ludovicopiero/nixpackages' # Don't do this in forks
    runs-on: ubuntu-latest
    outputs:
      id: pr
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PR_TOKEN }}"

      - name: Install nix
        uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Git config
        run: |
          git config --global user.email "maximiliansforza@proton.me"
          git config --global user.name "Maximilian Sforza"

      - name: Run nvfetcher
        run: |
          pushd pkgs
          rm -r _sources/wezterm-*
          nix run github:berberman/nvfetcher -- --commit-changes
          popd

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.PR_TOKEN }}"
          title: "Package Update"
          body: "BOOMP BOOMP"
          labels: automated,uwu, keep-up-to-date
          branch: "nvfetcher-update"
          delete-branch: true

  nix-update:
    if: github.repository == 'ludovicopiero/nixpackages' # Don't do this in forks
    runs-on: ubuntu-latest
    outputs:
      id: pr
    strategy:
      matrix:
        packages: [iosevka-q, sarasa-gothic]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PR_TOKEN }}"

      - name: Install nix
        uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Git config
        run: |
          git config --global user.email "maximiliansforza@proton.me"
          git config --global user.name "Maximilian Sforza"

      - name: Run nix-update
        run: |
          nix run nixpkgs#nix-update -- --flake ${{ matrix.packages }} --commit

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.PR_TOKEN }}"
          title: "Package Update"
          body: "BOOMP BOOMP"
          labels: automated,uwu, keep-up-to-date
          branch: "nix-update"
          delete-branch: true
